<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    new Promise((resolve, reject) => {
        setTimeout(() => {
            reject(1)
        }, 1000)
    }).then(
        //正确,错误都可以写
        value => {
            console.log(value);
        }
    ).catch(
        //专门用于执行错误的回调函数
        reason => {
            console.log(reason);
        }
    )


    //创建一个value值为3的promise对象(原型对象的上的方法,实例对象上的方法)
    const p1 = new Promise((resolve, reject) => {
        resolve(3)
    })

    //promise的方法
    const p2 = Promise.resolve(3)
    const p3 = Promise.reject(4)
    p1.then(value => console.log('p1 value', value))
    p2.then(value => console.log('p2 value', value))
    p3.catch(reason => console.log('p3 value', reason))


    //当有一个失败时,执行失败的回调,值为失败的值
    const p4 = Promise.all([p1, p2, p3])
    p4.then(
        value => console.log('p4 onResolved', value),     //成功时输出一个数组,成功值的数组
        reason => console.log('p4 onRejected', reason)
    )

    //race方法: 和all的语法一样,但是结果不会是数组,只有一个值,值为最先执行完的promise,判断其结果是正确还是失败,执行对应的回调
</script>
</body>
</html>